FROM pytorch/pytorch:2.1.2-cuda11.8-cudnn8-devel
ENV DEBIAN_FRONTEND=noninteractive
WORKDIR /app

# Install system dependencies
# ninja-build is required for mamba-ssm compilation
RUN apt-get update && apt-get install -y git build-essential ninja-build && rm -rf /var/lib/apt/lists/*

COPY requirements_torch.txt .
# Install packaging first as it's often a build dependency
RUN pip install --no-cache-dir packaging
RUN pip install --no-cache-dir -r requirements_torch.txt

COPY . .
ENV PYTHONPATH="${PYTHONPATH}:/app"
CMD ["python", "scripts/train_torch.py"]
