FROM pytorch/pytorch:2.1.2-cuda11.8-cudnn8-devel
ENV DEBIAN_FRONTEND=noninteractive
WORKDIR /app
RUN apt-get update && apt-get install -y git build-essential && rm -rf /var/lib/apt/lists/*
COPY requirements_torch.txt .
RUN pip install --no-cache-dir -r requirements_torch.txt
COPY . .
ENV PYTHONPATH="${PYTHONPATH}:/app/src"
CMD ["python", "scripts/train_torch.py"]
