from config.runtime import Config


def _get(name, default=None):
    return getattr(Config, name, default)


def main():
    print("🧭 Active Config Summary")
    print(f"   DEVICE: {_get('DEVICE')}")
    print(f"   BASE_DIR: {_get('BASE_DIR')}")
    print("")
    print("🔹 Data Paths")
    print(f"   PATH_HR: {_get('PATH_HR')}")
    print(f"   PATH_LR: {_get('PATH_LR')}")
    print(f"   PATH_STATIC: {_get('PATH_STATIC')}")
    print(f"   PATH_CACHE: {_get('PATH_CACHE')}")
    print(f"   STATS_PATH: {_get('STATS_PATH')}")
    print(f"   STATIC_CACHE_PATH: {_get('STATIC_CACHE_PATH')}")
    print("")
    print("🔹 Training")
    print(f"   SEED: {_get('SEED')}")
    print(f"   BATCH_SIZE: {_get('BATCH_SIZE')}")
    print(f"   GRADIENT_ACCUMULATION_STEPS: {_get('GRADIENT_ACCUMULATION_STEPS', 'n/a')}")
    print(f"   EFFECTIVE_BATCH_SIZE: {_get('EFFECTIVE_BATCH_SIZE', 'n/a')}")
    print(f"   EPOCHS: {_get('EPOCHS')}")
    print(f"   LEARNING_RATE: {_get('LEARNING_RATE')}")
    print(f"   SEQ_LEN: {_get('SEQ_LEN')}")
    print(f"   MIXED_PRECISION: {_get('MIXED_PRECISION')}")
    print("")
    print("🔹 Shapes & Channels")
    print(f"   LR_SHAPE: {_get('LR_SHAPE')}")
    print(f"   HR_SHAPE: {_get('HR_SHAPE')}")
    print(f"   CHANNELS: {_get('CHANNELS')}")
    print(f"   STATIC_CHANNELS: {_get('STATIC_CHANNELS')}")
    print("")
    print("🔹 Temporal Sampling")
    print(f"   TEMPORAL_STRIDE: {_get('TEMPORAL_STRIDE')}")
    print(f"   TEMPORAL_SAMPLER: {_get('TEMPORAL_SAMPLER')}")
    print(f"   TEMPORAL_WEIGHT_GAMMA: {_get('TEMPORAL_WEIGHT_GAMMA')}")
    print(f"   TEMPORAL_MIN_PROB: {_get('TEMPORAL_MIN_PROB')}")
    print(f"   TEMPORAL_SEASON_BALANCE: {_get('TEMPORAL_SEASON_BALANCE')}")
    print(f"   STATION_GRIB_PATH: {_get('STATION_GRIB_PATH')}")
    print("")
    print("🔹 Tile Training (Optional)")
    print(f"   PATCH_SIZE: {_get('PATCH_SIZE')}")
    print(f"   PATCHES_PER_EPOCH: {_get('PATCHES_PER_EPOCH')}")
    print(f"   VAL_PATCHES_PER_EPOCH: {_get('VAL_PATCHES_PER_EPOCH')}")
    print(f"   TILE_SAMPLER: {_get('TILE_SAMPLER')}")
    print(f"   TILE_WEIGHT_ALPHA: {_get('TILE_WEIGHT_ALPHA')}")
    print(f"   TILE_WEIGHT_GAMMA: {_get('TILE_WEIGHT_GAMMA')}")
    print(f"   TILE_MIN_PROB: {_get('TILE_MIN_PROB')}")
    print(f"   TILE_ERROR_MAP_PATH: {_get('TILE_ERROR_MAP_PATH')}")
    print("")
    print("🔹 Splits")
    print(f"   SPLIT_MODE: {_get('SPLIT_MODE')}")
    print(f"   TRAIN: {_get('TRAIN_START')} -> {_get('TRAIN_END')}")
    print(f"   VAL: {_get('VAL_START')} -> {_get('VAL_END')}")
    print(f"   TEST: {_get('TEST_START')} -> {_get('TEST_END')}")


if __name__ == "__main__":
    main()
